version: '2'
services:
    node:
        build: ./services/node
        image: registry.factory.trsb.net/angular-cli/node:7
        volumes:
            - ../:/workspace
    http:
        image: nginx:1.11.5-alpine
        volumes:
            - ./services/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
            - ../:/usr/share/nginx/html
